Models/ErrorViewModel.cs
namespace HerhalingASPdotnetCore.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/User.cs
using System.ComponentModel.DataAnnotations;

namespace HerhalingASPdotnetCore.Models
{
    public class User()
    {
        [Required(ErrorMessage ="{0} Required")]
        [DataType(DataType.Text)]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Too short or too long")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "Only letters and spaces allowed")]
        [Display(ResourceType = typeof(Resources.Models.User), Name = "Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "{0} Required")]
        [EmailAddress]
        [Display(ResourceType = typeof(Resources.Models.User), Name = "Email")]
        public string Email { get; set; }
        [Required(ErrorMessage = "{0} Required")]
        [StringLength(100, MinimumLength = 10,ErrorMessage ="Too short or too long")]
        [Display(ResourceType = typeof(Resources.Models.User), Name = "Message")]
        public string Message { get; set; }
    }
}

Controllers/CustomController.cs
using HerhalingASPdotnetCore.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Options;

namespace HerhalingASPdotnetCore.Controllers
{
    public class CustomController : Controller
    {
        private readonly ILogger<CustomController> _logger;
        private readonly IOptions<CustomController> _options;
        private readonly IStringLocalizer<CustomController> _localizer;

        public CustomController(ILogger<CustomController> logger, IStringLocalizer<CustomController> localizer, IOptions<CustomController> options)
        {
            _logger = logger;
            _options = options;
            _localizer = localizer;
        }
        public IActionResult Index()
        {
            var user = new User()
            {
                Name = "John Doe",
                Email = "test@test.com",
                Message = "Hello World!"
            };
            return View(user);
        }

        [HttpGet]
        public IActionResult Form()
        {
            return View(new User());
        }
        [HttpPost]
        public IActionResult Form(User user)
        {
            //if model is not valid, return the form view with the user object
            if (!ModelState.IsValid)
            {
                return View(user);
            }
            return View(user);
        }
    }
}

Controllers/HomeController.cs
using HerhalingASPdotnetCore.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HerhalingASPdotnetCore.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult LoremIpsum()
        {
            return View();
        }
        /// <summary>
        /// SignalR view
        /// </summary>
        /// <returns>SignalR view</returns>
        public IActionResult SignalR()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Custom/Form.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Localization
@inject IViewLocalizer ViewLocalizer
@inject IStringLocalizer<HerhalingASPdotnetCore.Models.User> Localizer
@model HerhalingASPdotnetCore.Models.User
@{
    Layout = "_CustomLayout";
}
<div class="text-center">
    <form asp-controller="Custom" asp-action="Form" asp-antiforgery="true">
        <label asp-for="Name"></label>
        <input id="userInput" asp-for="Name" />
        <span asp-validation-for="Name"></span>
        <br>
        <label asp-for="Email"></label>
        <input id="emailInput" asp-for="Email" />
        <span asp-validation-for="Email"></span>
        <br>
        <label asp-for="Message"></label>
        @Html.TextAreaFor(model => model.Message, new { @id = "messageInput"})
        <span asp-validation-for="Message"></span>
        <br>
        <input type="submit" id="sendButton" value=@ViewLocalizer["submit"] />
    </form>

    <hr />
    <br>
    <ul id="messagesList"></ul>
    <br>
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/chat.js"></script>
</div>
@{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

Views/Custom/Index.cshtml
@using System.Globalization
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer ViewLocalizer
@{
    Layout = "_CustomLayout";
}
@model HerhalingASPdotnetCore.Models.User

<div class="text-center">
    <h1>@ViewLocalizer["Culture"]: @CultureInfo.CurrentCulture.NativeName </h1>
    <p>@Model.Name</p>
    <p>@Model.Email</p>
    <p>@Model.Message</p>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer ViewLocalizer

<div class="text-center">
    <h1 class="display-4">@ViewLocalizer["Welcome to the homepage"]</h1>
    <br>
    <environment include="Production">
        <p>@ViewLocalizer["We are in production"]</p>
    </environment>
    <environment exclude="Production">
        <p>@ViewLocalizer["We are in development"]</p>
    </environment>
</div>

Views/Home/LoremIpsum.cshtml
@{
    ViewData["Title"] = "Lorem Ipsum";
}

<div class="text-center">
    <h1>@ViewData["Title"]</h1>
    <lorem></lorem>
</div>

Views/Home/SignalR.cshtml
@{
    ViewData["Title"] = "Signal R";
}

<div class="text-center">
    <div class="container">
        <div class="row p-1">
            <div class="col-1">User</div>
            <div class="col-5"><input type="text" id="userInput" /></div>
        </div>
        <div class="row p-1">
            <div class="col-1">Message</div>
            <div class="col-5"><input type="text" class="w-100" id="messageInput" /></div>
        </div>
        <div class="row p-1">
            <div class="col-6 text-end">
                <input type="button" id="sendButton" value="Send Message" />
            </div>
        </div>
        <div class="row p-1">
            <div class="col-6">
                <hr />
            </div>
        </div>
        <div class="row p-1">
            <div class="col-6">
                <ul id="messagesList"></ul>
            </div>
        </div>
    </div>
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/chat.js"></script>

</div>

Views/Shared/_CustomLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HerhalingASPdotnetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HerhalingASPdotnetCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HerhalingASPdotnetCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Custom" asp-action="Index">Custom</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Custom" asp-action="Form">Form</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HerhalingASPdotnetCore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HerhalingASPdotnetCore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HerhalingASPdotnetCore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="LoremIpsum">Lorem Ipsum</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Custom" asp-action="Index">Custom</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="SignalR">SignalR</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - HerhalingASPdotnetCore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>